### ISSUE TITLE
Looking for new maintainers

### ISSUE THREAD

**Issue by anthonynsimon** [ever-co/ever-traduora#197]
Hello all,
 
Just wanted to inform you that I no longer have the time to properly maintain this project.
 
It's been a long period of mainly solving minor issues and merging security patches, but haven't been able to do important feature work.
 
I believe it's time to either pass the torch to someone who can take Traduora to v1.0, or to discourage further production use as I can no longer maintain the project.
 
Last but not least: I want to thank everyone who has been involved in the project in one way or another. I highly appreciate your feedback, contributions, and encouragement. It's been a fun ride!

**Comment by evereq** [comment]
Hi @anthonynsimon, thank you for a great project!

We are building open-source based software in a similar stack (Nest + Angular) and potentially might be interested to integrate Traduora. At the moment we are using CrowdIn (they provided us with a cool subscription option for free!). However because our solutions are open-source we could integrate Traduora to allow customers to use it for they own translations, etc. Our software is https://github.com/ever-co/gauzy and https://github.com/ever-co/ever. 

Please let me know if you are interested to discuss this in more detail, my email displayed at https://github.com/evereq.

**Comment by anthonynsimon** [comment]
After chatting with @evereq I'm happy to announce that Traduora found a new home ❤️

I'm certain that the community and the project is in good hands with Ruslan and his organization.

More details will follow soon.

**Comment by evereq** [comment]
Thank you @anthonynsimon and all previous contributors for the amazing project and for the opportunity to move it forward! 🚀 

We plan to keep it as a separate product/project under the same license (AGPL), improve it and integrate with it from a few of our other products (<https://github.com/ever-co/ever-demand> and <https://github.com/ever-co/ever-gauzy>, both released with the same AGPL v3 license as Traduora).

Great times ahead for all Ever products!
If anyone will have any questions/suggestions, feel free to shoot us an email at <ever@ever.co>.

Thank you all again,
Ruslan
